apiVersion: v1
kind: Service
metadata:
  name: eks-example
  namespace: webserver
  labels:
    app: eks-example
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: eks-example

